version: "3.8"
services:
  database:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=securityproject
      - POSTGRES_PASSWORD=Security#01
      - POSTGRES_DB=securitydb
    expose:
      - 5432
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - database