version: "3.8"
services:
  database:
    image: postgres:13-alpine
    environment:
    - POSTGRES_USER=securityproject
    - POSTGRES_PASSWORD=Security#01
    - POSTGRES_DB=securitydb
    expose:
    - 5432
    volumes:
    - ".:/app:rw"
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - database
    volumes:
    - ".:/app:rw"
    - "./data:/data:rw"
    links:
    - "database"