# Generated by Django 3.1.3 on 2020-11-14 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(max_length=100)),
                ('content_text', models.CharField(max_length=2100)),
                ('blogScore', models.IntegerField(default=0)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=30)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('comment_text', models.CharField(max_length=700)),
                ('commentScore', models.IntegerField(default=0)),
                ('Blogs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_Blogs.blogs')),
            ],
        ),
    ]
