# Generated by Django 3.1.3 on 2020-11-14 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_Blogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(max_length=100)),
                ('creator', models.CharField(max_length=30)),
                ('content_text', models.CharField(max_length=2100)),
                ('blogScore', models.IntegerField(default=0)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='Blogs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_Blogs.blog'),
        ),
        migrations.DeleteModel(
            name='Blogs',
        ),
    ]
