# Generated by Django 3.1.3 on 2020-11-14 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_Blogs', '0002_auto_20201114_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='content_text',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='blogScore',
            new_name='score',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='title_text',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_text',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='commentScore',
            new_name='score',
        ),
    ]
