# Generated by Django 3.1.3 on 2020-11-14 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_Blogs', '0003_auto_20201114_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='edited',
            field=models.BooleanField(default=False),
        ),
    ]
